import React from "react";
import {
  Audio,
  Sequence,
  interpolate,
  staticFile,
  useVideoConfig,
} from "remotion";
import { SCENES, TOTAL_DURATION } from "./timing";

// Assets live in remotion/public/audio and are generated by
// scripts/generate-video-audio.mjs (npm run video:audio).

const COUNTDOWN_START = SCENES.question;
const PER_TICK = SCENES.countdown / 6; // 5,4,3,2,1,0
const URGENT_FROM = 4; // ticks for "1" and "0" get the sharper sound

/**
 * The full soundtrack: a quiet ambient bed under everything (silence reads as
 * "ad" in the Shorts feed), a tick on every countdown second, a chime when the
 * timer runs out, and an optional per-question voiceover on top.
 */
export const Soundtrack: React.FC<{ voiceover?: string }> = ({ voiceover }) => {
  const { fps } = useVideoConfig();

  return (
    <>
      <Audio
        src={staticFile("audio/bed.wav")}
        volume={(f) =>
          // Ease out over the last second so the loop-back replay never pops.
          interpolate(f, [TOTAL_DURATION - fps, TOTAL_DURATION], [0.5, 0], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          })
        }
      />

      {voiceover ? (
        <Audio src={staticFile(voiceover)} volume={1} />
      ) : null}

      {Array.from({ length: 6 }, (_, i) => (
        <Sequence
          key={`tick-${i}`}
          from={Math.round(COUNTDOWN_START + i * PER_TICK)}
          durationInFrames={Math.ceil(PER_TICK)}
        >
          <Audio
            src={staticFile(
              i >= URGENT_FROM ? "audio/tick-urgent.wav" : "audio/tick.wav",
            )}
            volume={0.8}
          />
        </Sequence>
      ))}

      <Sequence
        from={COUNTDOWN_START + SCENES.countdown}
        durationInFrames={Math.round(1.1 * fps)}
      >
        <Audio src={staticFile("audio/chime.wav")} volume={0.9} />
      </Sequence>
    </>
  );
};
