-- Drop the old CHECK constraint that was auto-generated by Hibernate with a limited set of types.
-- Re-add it with the full TestType enum values so all types are accepted.

ALTER TABLE assessment_tests DROP CONSTRAINT IF EXISTS assessment_tests_type_check;

ALTER TABLE assessment_tests
    ADD CONSTRAINT assessment_tests_type_check
    CHECK (type IN (
        'NUMERICAL_REASONING',
        'LOGICAL_REASONING',
        'VERBAL_REASONING',
        'ABSTRACT_REASONING',
        'CRITICAL_THINKING',
        'INDUCTIVE_REASONING',
        'DEDUCTIVE_REASONING',
        'DIAGRAMMATIC_REASONING',
        'SPATIAL_REASONING',
        'MECHANICAL_REASONING',
        'ANALYTICAL_THINKING',
        'DATA_INTERPRETATION',
        'ERROR_CHECKING',
        'READING_COMPREHENSION',
        'GRAMMAR_SPELLING',
        'WRITING_ASSESSMENT',
        'COMMUNICATION_SKILLS',
        'PRESENTATION_SKILLS',
        'PERSONALITY_WORK_STYLE',
        'SITUATIONAL_JUDGEMENT',
        'EMOTIONAL_INTELLIGENCE',
        'ADAPTABILITY',
        'CULTURAL_FIT',
        'LEADERSHIP_ASSESSMENT',
        'DECISION_MAKING',
        'STRATEGIC_THINKING',
        'PROJECT_MANAGEMENT',
        'TIME_MANAGEMENT',
        'RISK_ASSESSMENT',
        'TEAMWORK_COLLABORATION',
        'CONFLICT_RESOLUTION',
        'NEGOTIATION_SKILLS',
        'CUSTOMER_SERVICE',
        'SALES_APTITUDE',
        'FINANCIAL_LITERACY',
        'EXCEL_SKILLS',
        'CODING_CHALLENGE',
        'ETHICS_COMPLIANCE',
        'CREATIVITY_INNOVATION'
    ));
