package com.assesspro.backend.ai;

import org.springframework.stereotype.Component;

/**
 * Mock AI client that returns hard-coded JSON.
 *
 * TODO: Remove this class and register a real AiClient bean when connecting to a live AI provider.
 * For OpenAI: inject RestTemplate / WebClient, POST to https://api.openai.com/v1/chat/completions
 * For Anthropic Claude: POST to https://api.anthropic.com/v1/messages
 */
@Component
public class MockAiClient implements AiClient {

    @Override
    public String generateTest(String prompt) {
        // Returns sample JSON for a NUMERICAL_REASONING test.
        // Question 1 has an IMAGE media item; Question 2 has no media.
        return """
                {
                  "title": "Numerical Reasoning Practice",
                  "description": "A medium difficulty numerical reasoning test generated by AI.",
                  "type": "NUMERICAL_REASONING",
                  "difficulty": "MEDIUM",
                  "language": "EN",
                  "estimatedTimeMinutes": 12,
                  "questions": [
                    {
                      "questionText": "A company's annual revenue was €1,000,000 in 2021 and €1,400,000 in 2023. What is the percentage increase?",
                      "explanation": "(1,400,000 - 1,000,000) / 1,000,000 × 100 = 40%.",
                      "orderIndex": 1,
                      "mediaItems": [],
                      "answerOptions": [
                        { "answerText": "20%", "isCorrect": false, "orderIndex": 1 },
                        { "answerText": "30%", "isCorrect": false, "orderIndex": 2 },
                        { "answerText": "40%", "isCorrect": true,  "orderIndex": 3 },
                        { "answerText": "50%", "isCorrect": false, "orderIndex": 4 }
                      ]
                    },
                    {
                      "questionText": "A train travels 360 km in 3 hours. What is its average speed in km/h?",
                      "explanation": "Average speed = total distance / total time = 360 / 3 = 120 km/h.",
                      "orderIndex": 2,
                      "mediaItems": [],
                      "answerOptions": [
                        { "answerText": "90 km/h",  "isCorrect": false, "orderIndex": 1 },
                        { "answerText": "100 km/h", "isCorrect": false, "orderIndex": 2 },
                        { "answerText": "120 km/h", "isCorrect": true,  "orderIndex": 3 },
                        { "answerText": "150 km/h", "isCorrect": false, "orderIndex": 4 }
                      ]
                    },
                    {
                      "questionText": "If a product costs €80 after a 20% discount, what was the original price?",
                      "explanation": "Let x be the original price. x × 0.80 = 80, so x = 80 / 0.80 = €100.",
                      "orderIndex": 3,
                      "mediaItems": [],
                      "answerOptions": [
                        { "answerText": "€90",  "isCorrect": false, "orderIndex": 1 },
                        { "answerText": "€95",  "isCorrect": false, "orderIndex": 2 },
                        { "answerText": "€100", "isCorrect": true,  "orderIndex": 3 },
                        { "answerText": "€110", "isCorrect": false, "orderIndex": 4 }
                      ]
                    },
                    {
                      "questionText": "In a company of 200 employees, 35% work part-time. How many employees work full-time?",
                      "explanation": "Part-time employees: 200 × 0.35 = 70. Full-time: 200 − 70 = 130.",
                      "orderIndex": 4,
                      "mediaItems": [],
                      "answerOptions": [
                        { "answerText": "120", "isCorrect": false, "orderIndex": 1 },
                        { "answerText": "130", "isCorrect": true,  "orderIndex": 2 },
                        { "answerText": "140", "isCorrect": false, "orderIndex": 3 },
                        { "answerText": "150", "isCorrect": false, "orderIndex": 4 }
                      ]
                    },
                    {
                      "questionText": "What is 15% of 240?",
                      "explanation": "240 × 0.15 = 36.",
                      "orderIndex": 5,
                      "mediaItems": [],
                      "answerOptions": [
                        { "answerText": "24", "isCorrect": false, "orderIndex": 1 },
                        { "answerText": "30", "isCorrect": false, "orderIndex": 2 },
                        { "answerText": "36", "isCorrect": true,  "orderIndex": 3 },
                        { "answerText": "42", "isCorrect": false, "orderIndex": 4 }
                      ]
                    }
                  ]
                }
                """;
    }
}
