package com.assesspro.backend.entity.enums;

public enum TestType {
    NUMERICAL_REASONING,
    LOGICAL_REASONING,
    VERBAL_REASONING,
    SITUATIONAL_JUDGEMENT,
    PERSONALITY_WORK_STYLE,
    DATA_INTERPRETATION,
    ABSTRACT_REASONING,
    CRITICAL_THINKING,
    CODING_CHALLENGE,
    LEADERSHIP_ASSESSMENT,
    WRITING_ASSESSMENT
}
