package com.assesspro.backend.entity.enums;

public enum TestType {
    // Cognitive & Reasoning
    NUMERICAL_REASONING,
    LOGICAL_REASONING,
    VERBAL_REASONING,
    ABSTRACT_REASONING,
    CRITICAL_THINKING,
    INDUCTIVE_REASONING,
    DEDUCTIVE_REASONING,
    DIAGRAMMATIC_REASONING,
    SPATIAL_REASONING,
    MECHANICAL_REASONING,
    ANALYTICAL_THINKING,

    // Data & Interpretation
    DATA_INTERPRETATION,
    ERROR_CHECKING,

    // Verbal & Written
    READING_COMPREHENSION,
    GRAMMAR_SPELLING,
    WRITING_ASSESSMENT,
    COMMUNICATION_SKILLS,
    PRESENTATION_SKILLS,

    // Personality & Behavioural
    PERSONALITY_WORK_STYLE,
    SITUATIONAL_JUDGEMENT,
    EMOTIONAL_INTELLIGENCE,
    ADAPTABILITY,
    CULTURAL_FIT,

    // Leadership & Management
    LEADERSHIP_ASSESSMENT,
    DECISION_MAKING,
    STRATEGIC_THINKING,
    PROJECT_MANAGEMENT,
    TIME_MANAGEMENT,
    RISK_ASSESSMENT,

    // Interpersonal & Professional
    TEAMWORK_COLLABORATION,
    CONFLICT_RESOLUTION,
    NEGOTIATION_SKILLS,
    CUSTOMER_SERVICE,
    SALES_APTITUDE,

    // Domain-specific
    FINANCIAL_LITERACY,
    EXCEL_SKILLS,
    CODING_CHALLENGE,

    // Values & Ethics
    ETHICS_COMPLIANCE,

    // Creative
    CREATIVITY_INNOVATION
}
